name: Build and Deploy Docker App to AWS EC2

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t my-app .

      - name: Save Docker image as tar
        run: docker save my-app -o my-app.tar

      - name: Show host and enable verbose SSH
        run: |
          echo "HOST=${{ secrets.AWS_HOST }}"
          mkdir -p ~/.ssh
          printf "Host *\n  StrictHostKeyChecking no\n" > ~/.ssh/config

      - name: Test SSH connectivity
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ec2-user
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            echo "Connected OK"
            uname -a

      - name: Copy image to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ec2-user
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          source: "my-app.tar"
          target: "~/"
          debug: true

      - name: SSH into EC2 and run container
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ec2-user
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            docker load -i ~/my-app.tar
            docker stop my-app || true
            docker rm my-app || true
            docker run -d -p 80:5000 --name my-app my-app
